# This file was generated by GoReleaser. DO NOT EDIT.
cask "codegrapher" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "dfb88372fc790175e6ae60a2f7de021e5fadc4768ef4985feb9bd77d40db9042"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a595c336b32c3678977ff72840a6cf8f0762b0c61d276429dc34ac6b529efc6"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ebc0e4a308d396aba121bf07a13aa8174f9964e5a2bf56d5622e54743d17e9c8"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "702081dab8fbf6309bdfc03e822f6e6debf61c49629ace38b0069e35cb26c5af"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codegrapher"
  desc "codegrapher – a free Go tool that builds a graph of your codebase"
  homepage "https://github.com/code-grapher/codegrapher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codegrapher"

  # No zap stanza required
end
