# This file was generated by GoReleaser. DO NOT EDIT.
cask "codegrapher" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "dd0c65c2040ee7ab0e18345c60728683550c90a2e1001bc8c9bdab3e846ce665"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b2d03f8c98607734205e55ab5aa12ec32f9523f86139ad7eb6d2da8a8974d5f1"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0e04731f65dde1929bf7452dc7c07d31cccb62efee85212202383d52c3609d68"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5f4f9422b560da7983b1da49d453811ba2aea6dc00972fe517fb8e9e1249f54a"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codegrapher"
  desc "codegrapher – a free Go tool that builds a graph of your codebase"
  homepage "https://github.com/code-grapher/codegrapher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codegrapher"

  # No zap stanza required
end
