# This file was generated by GoReleaser. DO NOT EDIT.
cask "codegrapher" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "850b438cc5a60a7a3553ebb884ea348f641acf3295cf75018817d129911d2d5f"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b040b85ba68b21d9bbb761bfeabe7b8ddbdf9294ad19360a75038bf7d405ba2"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6b8fd3886107dd07e175181b49cd5aceb196b1fdeffe16882ada9d5493fbaf9f"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31b537d66c0e799cc1fd9a400258428057ada5f4c520eb22812a6e916ae20849"
      url "https://github.com/code-grapher/codegrapher/releases/download/v#{version}/codegrapher_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codegrapher"
  desc "codegrapher – a free Go tool that builds a graph of your codebase"
  homepage "https://github.com/code-grapher/codegrapher"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codegrapher"

  # No zap stanza required
end
